"""Complete EGX ticker-to-company-name mapping.

Source: stockanalysis.com/list/egyptian-stock-exchange/ (April 2026)
Total: 222 listed securities on the Egyptian Exchange.
"""

EGX_TICKERS = {
    # === EGX30 Blue Chips ===
    "COMI": {"name_en": "Commercial International Bank (CIB)", "name_ar": "البنك التجاري الدولي", "sector": "Banking"},
    "TMGH": {"name_en": "Talaat Moustafa Group", "name_ar": "مجموعة طلعت مصطفى", "sector": "Real Estate"},
    "SWDY": {"name_en": "Elsewedy Electric", "name_ar": "السويدي إليكتريك", "sector": "Industrials"},
    "ETEL": {"name_en": "Telecom Egypt", "name_ar": "المصرية للاتصالات", "sector": "Telecom"},
    "MFPC": {"name_en": "Misr Fertilizer Production (MOPCO)", "name_ar": "موبكو للأسمدة", "sector": "Chemicals"},
    "EGAL": {"name_en": "Egypt Aluminum", "name_ar": "مصر للألومنيوم", "sector": "Industrials"},
    "EAST": {"name_en": "Eastern Company", "name_ar": "الشرقية إيسترن كومباني", "sector": "Consumer"},
    "ABUK": {"name_en": "Abu Qir Fertilizers", "name_ar": "أبو قير للأسمدة", "sector": "Chemicals"},
    "ALCN": {"name_en": "Alexandria Container & Cargo Handling", "name_ar": "الإسكندرية لتداول الحاويات", "sector": "Transportation"},
    "QNBE": {"name_en": "Qatar National Bank (Egypt)", "name_ar": "بنك قطر الوطني مصر", "sector": "Banking"},
    "HDBK": {"name_en": "Housing & Development Bank", "name_ar": "بنك التعمير والإسكان", "sector": "Banking"},
    "EFIH": {"name_en": "e-finance for Digital & Financial Investments", "name_ar": "إي فاينانس للاستثمارات الرقمية", "sector": "Fintech"},
    "FWRY": {"name_en": "Fawry for Banking Technology", "name_ar": "فوري لتكنولوجيا البنوك", "sector": "Fintech"},
    "ORAS": {"name_en": "Orascom Construction", "name_ar": "أوراسكوم للإنشاءات", "sector": "Construction"},
    "ADIB": {"name_en": "Abu Dhabi Islamic Bank Egypt", "name_ar": "مصرف أبوظبي الإسلامي مصر", "sector": "Banking"},
    "EMFD": {"name_en": "Emaar Misr for Development", "name_ar": "إعمار مصر للتنمية", "sector": "Real Estate"},
    "HRHO": {"name_en": "EFG Holding", "name_ar": "إي إف جي القابضة", "sector": "Financial Services"},
    # === EGX70 & Other Listed ===
    "VLMR": {"name_en": "Valmore Holding", "name_ar": "فالمور القابضة", "sector": "Financial Services"},
    "VLMRA": {"name_en": "Valmore Holding (A)", "name_ar": "فالمور القابضة (أ)", "sector": "Financial Services"},
    "GPPL": {"name_en": "Golden Pyramids Plaza", "name_ar": "الأهرامات الذهبية", "sector": "Real Estate"},
    "EFID": {"name_en": "Edita Food Industries", "name_ar": "إيديتا للصناعات الغذائية", "sector": "Consumer"},
    "CIEB": {"name_en": "Credit Agricole Egypt", "name_ar": "كريدي أجريكول مصر", "sector": "Banking"},
    "IRON": {"name_en": "Egyptian Iron & Steel", "name_ar": "الحديد والصلب المصرية", "sector": "Steel"},
    "FERC": {"name_en": "Ferchem Misr for Fertilizers", "name_ar": "فيركيم مصر للأسمدة", "sector": "Chemicals"},
    "SCTS": {"name_en": "Suez Canal for Technology Settling", "name_ar": "قناة السويس للتكنولوجيا", "sector": "Technology"},
    "CANA": {"name_en": "Suez Canal Bank", "name_ar": "بنك قناة السويس", "sector": "Banking"},
    "JUFO": {"name_en": "Juhayna Food Industries", "name_ar": "جهينة للصناعات الغذائية", "sector": "Consumer"},
    "BTFH": {"name_en": "Beltone Holding", "name_ar": "بلتون القابضة", "sector": "Financial Services"},
    "ORHD": {"name_en": "Orascom Development Egypt", "name_ar": "أوراسكوم للتنمية", "sector": "Real Estate"},
    "FAIT": {"name_en": "Faisal Islamic Bank of Egypt", "name_ar": "بنك فيصل الإسلامي المصري", "sector": "Banking"},
    "FAITA": {"name_en": "Faisal Islamic Bank (A)", "name_ar": "بنك فيصل الإسلامي (أ)", "sector": "Banking"},
    "GBCO": {"name_en": "GB Corp", "name_ar": "جي بي كورب", "sector": "Automotive"},
    "OCDI": {"name_en": "SODIC (Sixth of October Development)", "name_ar": "سوديك للتنمية", "sector": "Real Estate"},
    "VALU": {"name_en": "U Consumer Finance", "name_ar": "يو للتمويل الاستهلاكي", "sector": "Fintech"},
    "PHDC": {"name_en": "Palm Hills Developments", "name_ar": "بالم هيلز للتعمير", "sector": "Real Estate"},
    "EXPA": {"name_en": "Export Development Bank of Egypt", "name_ar": "البنك المصري لتنمية الصادرات", "sector": "Banking"},
    "EGCH": {"name_en": "Egyptian Chemical Industries", "name_ar": "الكيماويات المصرية", "sector": "Chemicals"},
    "RAYA": {"name_en": "Raya Holding", "name_ar": "راية القابضة", "sector": "Technology"},
    "HELI": {"name_en": "Heliopolis Housing", "name_ar": "مصر الجديدة للإسكان", "sector": "Real Estate"},
    "ARCC": {"name_en": "Arabian Cement Company", "name_ar": "العربية للأسمنت", "sector": "Cement"},
    "EFIC": {"name_en": "Egyptian Financial & Industrial", "name_ar": "المصرية المالية والصناعية", "sector": "Financial Services"},
    "SKPC": {"name_en": "Sidi Kerir Petrochemicals", "name_ar": "سيدي كرير للبتروكيماويات", "sector": "Chemicals"},
    "CLHO": {"name_en": "Cleopatra Hospitals Group", "name_ar": "مجموعة مستشفيات كليوباترا", "sector": "Healthcare"},
    "CCAP": {"name_en": "QALA For Financial Investments", "name_ar": "قلعة للاستثمارات المالية", "sector": "Financial Services"},
    "TAQA": {"name_en": "TAQA Arabia", "name_ar": "طاقة عربية", "sector": "Energy"},
    "MCQE": {"name_en": "Misr Cement (Qena)", "name_ar": "أسمنت مصر قنا", "sector": "Cement"},
    "POUL": {"name_en": "Cairo Poultry Company", "name_ar": "القاهرة للدواجن", "sector": "Consumer"},
    "SAUD": {"name_en": "alBaraka Bank Egypt", "name_ar": "بنك البركة مصر", "sector": "Banking"},
    "EGSA": {"name_en": "Nilesat (Egyptian Satellite Co.)", "name_ar": "نايل سات", "sector": "Telecom"},
    "SCEM": {"name_en": "Sinai Cement", "name_ar": "أسمنت سيناء", "sector": "Cement"},
    "ORWE": {"name_en": "Oriental Weavers", "name_ar": "النساجون الشرقيون", "sector": "Consumer"},
    "UBEE": {"name_en": "The United Bank", "name_ar": "البنك المتحد", "sector": "Banking"},
    "MTIE": {"name_en": "MM Group for Industry & Trade", "name_ar": "مجموعة إم إم للصناعة والتجارة", "sector": "Industrials"},
    "PHAR": {"name_en": "Egyptian Int'l Pharmaceutical (EIPICO)", "name_ar": "المصرية الدولية للصناعات الدوائية", "sector": "Pharma"},
    "MBSC": {"name_en": "Misr Beni Suef Cement", "name_ar": "أسمنت مصر بني سويف", "sector": "Cement"},
    "MASR": {"name_en": "Madinet Masr Housing & Development", "name_ar": "مدينة مصر للإسكان", "sector": "Real Estate"},
    "CICH": {"name_en": "CI Capital Holding", "name_ar": "سي آي كابيتال القابضة", "sector": "Financial Services"},
    "TALM": {"name_en": "Taaleem Management Services", "name_ar": "تعليم لخدمات الإدارة", "sector": "Education"},
    "ATQA": {"name_en": "Misr National Steel (Ataqa)", "name_ar": "مصر الوطنية للصلب العتاقة", "sector": "Steel"},
    "MOIL": {"name_en": "Maridive & Oil Services", "name_ar": "ماريدايف لخدمات البترول", "sector": "Energy"},
    "AMOC": {"name_en": "Alexandria Mineral Oils", "name_ar": "الإسكندرية للزيوت المعدنية", "sector": "Energy"},
    "ISPH": {"name_en": "Ibnsina Pharma", "name_ar": "ابن سينا فارما", "sector": "Pharma"},
    "CIRA": {"name_en": "CIRA Education", "name_ar": "سيرا للتعليم", "sector": "Education"},
    "EGBE": {"name_en": "Egyptian Gulf Bank", "name_ar": "البنك المصري الخليجي", "sector": "Banking"},
    "MHOT": {"name_en": "Misr Hotels", "name_ar": "فنادق مصر", "sector": "Tourism"},
    "IFAP": {"name_en": "Int'l Co. for Agricultural Crops", "name_ar": "الدولية للمحاصيل الزراعية", "sector": "Agriculture"},
    "RMDA": {"name_en": "Tenth of Ramadan for Pharma", "name_ar": "العاشر من رمضان للأدوية", "sector": "Pharma"},
    "BINV": {"name_en": "B Investments Holding", "name_ar": "بي للاستثمارات القابضة", "sector": "Financial Services"},
    "CSAG": {"name_en": "Canal Shipping Agencies", "name_ar": "وكالات الملاحة لقناة السويس", "sector": "Transportation"},
    "SPHT": {"name_en": "El Shams Pyramids Hotels & Tourism", "name_ar": "شمس الأهرامات للفنادق والسياحة", "sector": "Tourism"},
    "OLFI": {"name_en": "Obour Land for Food Industries", "name_ar": "أراضي العبور للصناعات الغذائية", "sector": "Consumer"},
    "EGTS": {"name_en": "Egyptian Resorts Company", "name_ar": "المنتجعات المصرية", "sector": "Real Estate"},
    "OIH": {"name_en": "Orascom Investment Holding", "name_ar": "أوراسكوم للاستثمار القابضة", "sector": "Diversified"},
    "BONY": {"name_en": "Bonyan for Development & Trade", "name_ar": "بنيان للتنمية والتجارة", "sector": "Real Estate"},
    "ISMQ": {"name_en": "Iron & Steel for Mines & Quarries", "name_ar": "الحديد والصلب للمناجم والمحاجر", "sector": "Mining"},
    "ELEC": {"name_en": "Electro Cable Egypt", "name_ar": "الكابلات الكهربائية المصرية", "sector": "Industrials"},
    "MIPH": {"name_en": "MINAPHARM Pharmaceuticals", "name_ar": "مينا فارم للأدوية", "sector": "Pharma"},
    "DOMT": {"name_en": "Domty (Arabian Food Industries)", "name_ar": "دومتي للصناعات الغذائية", "sector": "Consumer"},
    "SUGR": {"name_en": "Delta Sugar", "name_ar": "الدلتا للسكر", "sector": "Consumer"},
    "EGAS": {"name_en": "Egypt Gas", "name_ar": "الغاز المصرية", "sector": "Energy"},
    "AMES": {"name_en": "Alexandria New Medical Center", "name_ar": "مركز الإسكندرية الطبي الجديد", "sector": "Healthcare"},
    "MOIN": {"name_en": "Mohandes Insurance", "name_ar": "المهندس للتأمين", "sector": "Insurance"},
    "ACAP": {"name_en": "A Capital Holding", "name_ar": "أيه كابيتال القابضة", "sector": "Financial Services"},
    "MPRC": {"name_en": "Egyptian Media Production City", "name_ar": "مدينة الإنتاج الإعلامي", "sector": "Media"},
    "BIOC": {"name_en": "GlaxoSmithKline Egypt", "name_ar": "جلاكسو سميثكلاين مصر", "sector": "Pharma"},
    "ZMID": {"name_en": "Zahraa El Maadi Investment", "name_ar": "زهراء المعادي للاستثمار", "sector": "Real Estate"},
    "DSCW": {"name_en": "Dice Sport Wear", "name_ar": "دايس للملابس الجاهزة", "sector": "Consumer"},
    "SPIN": {"name_en": "Alexandria Spinning & Weaving", "name_ar": "الإسكندرية للغزل والنسيج", "sector": "Textiles"},
    "CNFN": {"name_en": "Contact Financial Holding", "name_ar": "كونتكت المالية القابضة", "sector": "Financial Services"},
    "NIPH": {"name_en": "El-Nile for Pharmaceuticals", "name_ar": "النيل للأدوية والكيماويات", "sector": "Pharma"},
    "PRDC": {"name_en": "Pioneers Properties (PRE Group)", "name_ar": "بايونيرز العقارية", "sector": "Real Estate"},
    "ENGC": {"name_en": "Industrial Engineering Co.", "name_ar": "الهندسية الصناعية للإنشاءات", "sector": "Construction"},
    "GOUR": {"name_en": "Gourmet Egypt Foods", "name_ar": "جورميه مصر للأغذية", "sector": "Consumer"},
    "NAPR": {"name_en": "National Printing Company", "name_ar": "الوطنية للطباعة", "sector": "Industrials"},
    "PHTV": {"name_en": "Pyramisa Hotels & Resorts", "name_ar": "بيراميزا للفنادق", "sector": "Tourism"},
    "CPCI": {"name_en": "Kahira Pharmaceuticals", "name_ar": "القاهرة للأدوية والكيماويات", "sector": "Pharma"},
    "GSSC": {"name_en": "General Co. for Silos & Storage", "name_ar": "العامة للصوامع والتخزين", "sector": "Logistics"},
    "AXPH": {"name_en": "Alexandria Pharmaceuticals", "name_ar": "الإسكندرية للأدوية", "sector": "Pharma"},
    "GDWA": {"name_en": "Gadwa for Industrial Development", "name_ar": "جدوى للتنمية الصناعية", "sector": "Industrials"},
    "MICH": {"name_en": "Misr Chemical Industries", "name_ar": "مصر للكيماويات", "sector": "Chemicals"},
    "WCDF": {"name_en": "Middle & West Delta Flour Mills", "name_ar": "مطاحن وسط وغرب الدلتا", "sector": "Consumer"},
    "SVCE": {"name_en": "South Valley Cement", "name_ar": "أسمنت الوادي الجنوبي", "sector": "Cement"},
    "MPCI": {"name_en": "Memphis Pharmaceuticals", "name_ar": "ممفيس للأدوية", "sector": "Pharma"},
    "SAIB": {"name_en": "Société Arabe Internationale de Banque", "name_ar": "المجموعة العربية الدولية للبنوك", "sector": "Banking"},
    "OCPH": {"name_en": "October Pharma", "name_ar": "أكتوبر فارما", "sector": "Pharma"},
    "UEFM": {"name_en": "Upper Egypt Flour Mills", "name_ar": "مطاحن صعيد مصر", "sector": "Consumer"},
    "KABO": {"name_en": "El-Nasr Clothing & Textiles (KABO)", "name_ar": "النصر للملابس والمنسوجات كابو", "sector": "Textiles"},
    "AMIA": {"name_en": "Arab Moltaqa Investments", "name_ar": "الملتقى العربي للاستثمارات", "sector": "Financial Services"},
    "GGRN": {"name_en": "Go Green for Agricultural Investment", "name_ar": "جو جرين للاستثمار الزراعي", "sector": "Agriculture"},
    "NINH": {"name_en": "Nozha International Hospital", "name_ar": "مستشفى النزهة الدولي", "sector": "Healthcare"},
    "MFSC": {"name_en": "Egypt Free Shops", "name_ar": "الأسواق الحرة المصرية", "sector": "Retail"},
    "CFGH": {"name_en": "Concrete Fashion Group", "name_ar": "كونكريت فاشون جروب", "sector": "Consumer"},
    "OFH": {"name_en": "OB Financial Holding", "name_ar": "أو بي المالية القابضة", "sector": "Financial Services"},
    "ARAB": {"name_en": "Arab Developers Holding", "name_ar": "المطورون العرب القابضة", "sector": "Real Estate"},
    "AJWA": {"name_en": "AJWA for Food Industries", "name_ar": "أجواء للصناعات الغذائية", "sector": "Consumer"},
    "ACAMD": {"name_en": "Arab Co. for Asset Management", "name_ar": "العربية لإدارة الأصول والتنمية", "sector": "Financial Services"},
    "KZPC": {"name_en": "Kafr El Zayat Pesticides", "name_ar": "كفر الزيات للمبيدات", "sector": "Chemicals"},
    "UNIT": {"name_en": "United Co. for Housing & Development", "name_ar": "المتحدة للإسكان والتعمير", "sector": "Real Estate"},
    "SDTI": {"name_en": "Sharm Dreams for Tourism Investment", "name_ar": "شرم دريمز للاستثمار السياحي", "sector": "Tourism"},
    "NAHO": {"name_en": "Naeem Holding", "name_ar": "نعيم القابضة", "sector": "Financial Services"},
    "SMFR": {"name_en": "Samad Misr (EGYFERT)", "name_ar": "سماد مصر", "sector": "Chemicals"},
    "ACGC": {"name_en": "Arabia Cotton Ginning", "name_ar": "العربية لحليج الأقطان", "sector": "Textiles"},
    "ADCI": {"name_en": "The Arab Drug Company", "name_ar": "العربية للأدوية", "sector": "Pharma"},
    "AFMC": {"name_en": "Alexandria Flour Mills", "name_ar": "مطاحن الإسكندرية", "sector": "Consumer"},
    "ASCM": {"name_en": "ASEC Mining (ASCOM)", "name_ar": "أسيك للتعدين", "sector": "Mining"},
    "LCSW": {"name_en": "Lecico Egypt", "name_ar": "ليسيكو مصر", "sector": "Industrials"},
    "ELKA": {"name_en": "Cairo Housing & Development", "name_ar": "القاهرة للإسكان والتعمير", "sector": "Real Estate"},
    "PHGC": {"name_en": "Premium Healthcare Group", "name_ar": "بريميم للرعاية الصحية", "sector": "Healthcare"},
    "EDFM": {"name_en": "East Delta Flour Mills", "name_ar": "مطاحن شرق الدلتا", "sector": "Consumer"},
    "ATLC": {"name_en": "Al Tawfeek Leasing", "name_ar": "التوفيق للتأجير التمويلي", "sector": "Financial Services"},
    "DAPH": {"name_en": "Development & Engineering Consultants", "name_ar": "التنمية والاستشارات الهندسية", "sector": "Pharma"},
    "INFI": {"name_en": "Ismailia National for Food Industries", "name_ar": "الإسماعيلية الوطنية للغذاء", "sector": "Consumer"},
    "ZEOT": {"name_en": "Extracted Oil & Derivatives", "name_ar": "الزيوت المستخلصة ومنتجاتها", "sector": "Consumer"},
    "ADPC": {"name_en": "Arab Dairy Products", "name_ar": "العربية لمنتجات الألبان", "sector": "Consumer"},
    "EALR": {"name_en": "Arab Co. for Land Reclamation", "name_ar": "العربية لاستصلاح الأراضي", "sector": "Agriculture"},
    "SNFC": {"name_en": "Sharkia National for Food Security", "name_ar": "الشرقية الوطنية للأمن الغذائي", "sector": "Consumer"},
    "ETRS": {"name_en": "Egyptian Transport (ETRANS)", "name_ar": "النقل والخدمات التجارية المصرية", "sector": "Transportation"},
    "RACC": {"name_en": "Raya Customer Experience", "name_ar": "راية لخدمة العملاء", "sector": "Technology"},
    "AMER": {"name_en": "Amer Group Holding", "name_ar": "عامر جروب القابضة", "sector": "Diversified"},
    "ELSH": {"name_en": "Al Shams Housing", "name_ar": "الشمس للإسكان والتعمير", "sector": "Real Estate"},
    "WKOL": {"name_en": "Wadi Kom Ombo Land Reclamation", "name_ar": "وادي كوم أمبو لاستصلاح الأراضي", "sector": "Agriculture"},
    "MPCO": {"name_en": "Mansoura Poultry", "name_ar": "المنصورة للدواجن", "sector": "Consumer"},
    "OBRI": {"name_en": "El-Ebour Real Estate Investment", "name_ar": "العبور للاستثمار العقاري", "sector": "Real Estate"},
    "GPIM": {"name_en": "GPI for Urban Growth", "name_ar": "جي بي آي للنمو العمراني", "sector": "Real Estate"},
    "EHDR": {"name_en": "Egyptians for Housing & Development", "name_ar": "المصريون للإسكان والتعمير", "sector": "Real Estate"},
    "DEIN": {"name_en": "Delta Insurance", "name_ar": "الدلتا للتأمين", "sector": "Insurance"},
    "ECAP": {"name_en": "Al Ezz Ceramics & Porcelain", "name_ar": "العز للسيراميك والبورسلين", "sector": "Industrials"},
    "SCFM": {"name_en": "South Cairo & Giza Flour Mills", "name_ar": "مطاحن جنوب القاهرة والجيزة", "sector": "Consumer"},
    "CEFM": {"name_en": "Middle Egypt Flour Mills", "name_ar": "مطاحن مصر الوسطى", "sector": "Consumer"},
    "MENA": {"name_en": "Mena for Tourism & Real Estate", "name_ar": "مينا للسياحة والاستثمار العقاري", "sector": "Tourism"},
    "ISMA": {"name_en": "Ismailia Misr Poultry", "name_ar": "الإسماعيلية مصر للدواجن", "sector": "Consumer"},
    "NDRL": {"name_en": "National Drilling Company", "name_ar": "الوطنية للحفر", "sector": "Energy"},
    "IDRE": {"name_en": "Ismailia Development & Real Estate", "name_ar": "الإسماعيلية للتنمية والاستثمار العقاري", "sector": "Real Estate"},
    "CERA": {"name_en": "The Arab Ceramics Co.", "name_ar": "العربية للسيراميك أراسيرام", "sector": "Industrials"},
    "NARE": {"name_en": "Naeem Real Estate Holding", "name_ar": "نعيم العقارية القابضة", "sector": "Real Estate"},
    "ODIN": {"name_en": "ODIN Investments", "name_ar": "أودن للاستثمارات", "sector": "Financial Services"},
    "ALRA": {"name_en": "Atlas for Investment & Food", "name_ar": "أطلس للاستثمار والصناعات الغذائية", "sector": "Consumer"},
    "MILS": {"name_en": "North Cairo Flour Mills", "name_ar": "مطاحن شمال القاهرة", "sector": "Consumer"},
    "AALR": {"name_en": "General Co. for Land Reclamation", "name_ar": "العامة لاستصلاح وتنمية الأراضي", "sector": "Agriculture"},
    "NCCW": {"name_en": "Nasr Company for Civil Works", "name_ar": "النصر للأعمال المدنية", "sector": "Construction"},
    "NHPS": {"name_en": "National Co. for Housing Prof. Syndicates", "name_ar": "الوطنية لإسكان النقابات المهنية", "sector": "Real Estate"},
    "MEPA": {"name_en": "Medical Packaging Company", "name_ar": "التعبئة الطبية", "sector": "Healthcare"},
    "UEGC": {"name_en": "El-Saeed Contracting & Real Estate", "name_ar": "السعيد للمقاولات والاستثمار العقاري", "sector": "Construction"},
    "POCO": {"name_en": "Port Said Containers & Cargo", "name_ar": "بورسعيد لتداول الحاويات", "sector": "Transportation"},
    "MOSC": {"name_en": "Misr Oils & Soap", "name_ar": "مصر للزيوت والصابون", "sector": "Consumer"},
    "MAAL": {"name_en": "Marseille Almasreia Alkhalegeya Holding", "name_ar": "مرسيليا المصرية الخليجية القابضة", "sector": "Real Estate"},
    "RTVC": {"name_en": "Remco Tourism Villages", "name_ar": "ريمكو للقرى السياحية", "sector": "Tourism"},
    "ALUM": {"name_en": "Arab Aluminum Company", "name_ar": "العربية للألومنيوم", "sector": "Industrials"},
    "SEIG": {"name_en": "Saudi Egyptian Investment & Finance", "name_ar": "السعودية المصرية للاستثمارات المالية", "sector": "Financial Services"},
    "SEIGA": {"name_en": "Saudi Egyptian Investment (A)", "name_ar": "السعودية المصرية للاستثمارات (أ)", "sector": "Financial Services"},
    "EBSC": {"name_en": "Osool ESB Securities Brokerage", "name_ar": "أصول إي إس بي للوساطة في الأوراق المالية", "sector": "Financial Services"},
    "SIPC": {"name_en": "Sabaa Int'l Pharmaceutical", "name_ar": "سبأ الدولية للأدوية", "sector": "Pharma"},
    "GTEX": {"name_en": "GTEX for Commercial & Industrial", "name_ar": "جي تكس للاستثمارات التجارية والصناعية", "sector": "Textiles"},
    "COSG": {"name_en": "Cairo Oil & Soap", "name_ar": "القاهرة للزيوت والصابون", "sector": "Consumer"},
    "MOED": {"name_en": "Egyptian Modern Education Systems", "name_ar": "نظم التعليم المصرية الحديثة", "sector": "Education"},
    "PRCL": {"name_en": "General Co. for Ceramic & Porcelain", "name_ar": "العامة للسيراميك والبورسلين", "sector": "Industrials"},
    "RREI": {"name_en": "Arab Real Estate Investment", "name_ar": "العربية للاستثمار العقاري", "sector": "Real Estate"},
    "ICLE": {"name_en": "International Co. for Leasing", "name_ar": "الدولية للتأجير التمويلي", "sector": "Financial Services"},
    "GGCC": {"name_en": "Giza General Contracting", "name_ar": "الجيزة العامة للمقاولات", "sector": "Construction"},
    "MEGM": {"name_en": "Middle East Glass Manufacturing", "name_ar": "الشرق الأوسط لصناعة الزجاج", "sector": "Industrials"},
    "APSW": {"name_en": "Unirab Polvara Spinning & Weaving", "name_ar": "يونيراب بولفارا للغزل والنسيج", "sector": "Textiles"},
    "RAKT": {"name_en": "Rakta Paper Manufacturing", "name_ar": "راكتا لصناعة الورق", "sector": "Industrials"},
    "PRMH": {"name_en": "Prime Holding", "name_ar": "برايم القابضة", "sector": "Financial Services"},
    "CAED": {"name_en": "Cairo Educational Services", "name_ar": "القاهرة للخدمات التعليمية", "sector": "Education"},
    "KRDI": {"name_en": "AlKhair River for Agricultural Investment", "name_ar": "نهر الخير للاستثمار الزراعي", "sector": "Agriculture"},
    "AIDC": {"name_en": "Arabia Investments & Development", "name_ar": "العربية للاستثمارات والتنمية", "sector": "Diversified"},
    "DTPP": {"name_en": "Delta for Printing & Packaging", "name_ar": "الدلتا للطباعة والتغليف", "sector": "Industrials"},
    "TANM": {"name_en": "Tanmiya for Real Estate Investment", "name_ar": "تنمية للاستثمار العقاري", "sector": "Real Estate"},
    "MCRO": {"name_en": "Macro Group Pharmaceuticals", "name_ar": "ماكرو جروب للأدوية", "sector": "Pharma"},
    "GTWL": {"name_en": "Golden Textiles & Wool", "name_ar": "النسيج الذهبي والصوف", "sector": "Textiles"},
    "UNIP": {"name_en": "Universal for Paper & Packaging", "name_ar": "يونيفرسال للورق والتغليف", "sector": "Industrials"},
    "AFDI": {"name_en": "Al Ahly for Development & Investment", "name_ar": "الأهلي للتنمية والاستثمار", "sector": "Financial Services"},
    "ASPI": {"name_en": "Aspire Capital Holding", "name_ar": "أسباير كابيتال القابضة", "sector": "Financial Services"},
    "RUBX": {"name_en": "Rubex International for Plastic", "name_ar": "روبكس الدولية للبلاستيك", "sector": "Industrials"},
    "SPMD": {"name_en": "Speed Medical", "name_ar": "سبيد ميديكال", "sector": "Healthcare"},
    "ARVA": {"name_en": "Arab Valves Company", "name_ar": "العربية للصمامات", "sector": "Industrials"},
    "ANFI": {"name_en": "Alexandria National for Financial Investment", "name_ar": "الإسكندرية الوطنية للاستثمار المالي", "sector": "Financial Services"},
    "ROTO": {"name_en": "Rowad Tourism Company", "name_ar": "رواد السياحة", "sector": "Tourism"},
    "AIHC": {"name_en": "Arabia Investments Holding", "name_ar": "العربية للاستثمارات القابضة", "sector": "Financial Services"},
    "KWIN": {"name_en": "El Kahera El Watania Investment", "name_ar": "القاهرة الوطنية للاستثمار", "sector": "Diversified"},
    "EEII": {"name_en": "Arab Engineering Industries", "name_ar": "العربية للصناعات الهندسية", "sector": "Industrials"},
    "AREH": {"name_en": "Real Estate Egyptian Consortium", "name_ar": "التجمع العقاري المصري", "sector": "Real Estate"},
    "GRCA": {"name_en": "Grand Capital for Financial Investments", "name_ar": "جراند كابيتال للاستثمارات المالية", "sector": "Financial Services"},
    "ICID": {"name_en": "International Co. for Investment & Development", "name_ar": "الدولية للاستثمار والتنمية", "sector": "Diversified"},
    "CRST": {"name_en": "Creast Mark for Contracting", "name_ar": "كريست مارك للمقاولات", "sector": "Construction"},
    "EPCO": {"name_en": "Egypt for Poultry", "name_ar": "مصر للدواجن", "sector": "Consumer"},
    "EASB": {"name_en": "Egyptian Arabian Securities Brokerage", "name_ar": "المصرية العربية ثمار للسمسرة", "sector": "Financial Services"},
    "DGTZ": {"name_en": "I Wave Beyond Expectations", "name_ar": "آي ويف", "sector": "Technology"},
    "ELWA": {"name_en": "El Wadi for Investment & Development", "name_ar": "الوادي للاستثمار والتنمية", "sector": "Real Estate"},
    "LUTS": {"name_en": "Lotus Agri Capital", "name_ar": "لوتس أجري كابيتال", "sector": "Agriculture"},
    "ELNA": {"name_en": "El Nasr for Agricultural Crops", "name_ar": "النصر للمحاصيل الزراعية", "sector": "Agriculture"},
    "GIHD": {"name_en": "Gharbia Islamic Housing Development", "name_ar": "الغربية الإسلامية للإسكان", "sector": "Real Estate"},
    "DCCC": {"name_en": "Damietta Container & Cargo Handling", "name_ar": "دمياط لتداول الحاويات", "sector": "Transportation"},
    "TRTO": {"name_en": "Trans Oceans Tours", "name_ar": "عبر المحيطات للسياحة", "sector": "Tourism"},
    "MMAT": {"name_en": "Marsa Alam Tourism Development", "name_ar": "مرسى علم للتنمية السياحية", "sector": "Tourism"},
    "NEDA": {"name_en": "Northern Upper Egypt Development & Agriculture", "name_ar": "شمال الصعيد للتنمية والإنتاج الزراعي", "sector": "Agriculture"},
    "EPPK": {"name_en": "El Ahram for Printing & Packaging", "name_ar": "الأهرام للطباعة والتغليف", "sector": "Industrials"},
    "CCRS": {"name_en": "Gulf Canadian for Arab Real Estate", "name_ar": "الخليج الكندي للاستثمار العقاري العربي", "sector": "Real Estate"},
    "GMCI": {"name_en": "GMC Group for Industrial & Commercial", "name_ar": "جي إم سي للاستثمارات الصناعية والتجارية", "sector": "Diversified"},
    "EOSB": {"name_en": "El Orouba Securities Brokerage", "name_ar": "العروبة للسمسرة في الأوراق المالية", "sector": "Financial Services"},
    "CPME": {"name_en": "Catalyst Partners", "name_ar": "كاتاليست بارتنرز", "sector": "Financial Services"},
    "COPR": {"name_en": "Copper for Commercial & Real Estate", "name_ar": "كوبر للاستثمار التجاري والعقاري", "sector": "Real Estate"},
    # === Legacy aliases ===
    "AUTO": {"name_en": "GB Auto (now GB Corp)", "name_ar": "جي بي أوتو", "sector": "Automotive"},
    "MNHD": {"name_en": "Madinet Nasr Housing (now MASR)", "name_ar": "مدينة نصر للإسكان", "sector": "Real Estate"},
    "ESRS": {"name_en": "Ezz Steel", "name_ar": "حديد عز", "sector": "Steel"},
    "EKHOA": {"name_en": "El Khair for Trade", "name_ar": "الخير للتجارة", "sector": "Consumer"},
    "AIIB": {"name_en": "Arab Investment Bank", "name_ar": "بنك الاستثمار العربي", "sector": "Banking"},
    "EKHO": {"name_en": "Edita Food Industries", "name_ar": "إيديتا للصناعات الغذائية", "sector": "Consumer"},
}


def get_company_names(ticker: str) -> dict:
    """Get company names for a ticker. Returns dict with name_en, name_ar, sector.

    If ticker not found, returns generic names based on the ticker symbol.
    """
    # Strip .CA suffix if present
    clean_ticker = ticker.upper().replace(".CA", "")

    if clean_ticker in EGX_TICKERS:
        return EGX_TICKERS[clean_ticker]

    # Fallback: use ticker as company name
    return {
        "name_en": clean_ticker,
        "name_ar": clean_ticker,
        "sector": "Unknown",
    }
